server:
  port: 8080

#  Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Public_DB
#    url: jdbc:mysql://${DB_HOST: localhost}:3306/Public_DB
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
